# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Set up Maven
      run: |
        export M2_HOME=/usr/local/apache-maven-3.8.4
        export MAVEN_HOME=$M2_HOME
        export PATH=$M2_HOME/bin:$PATH

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: List directory contents
      run: |
        echo "Listing direcotry contents:"
        ls -la
        echo "Listing kata-roman-numbers directory contents:"
        ls -la kata-roman-numbers
        
    - name: Build and Test with Maven
      working-directory: kata-roman-numbers
      run: |
        #!/bin/bash
        echo "Current directory:"
        pwd
        echo "Listing directory contents:"
        ls -la
        echo "Running Maven build and tests:"
        mvn -B package
        mvn test
        
    - name: Super Linter
      uses: github/super-linter@v5
      env:
        VALIDATE_ALL_CODEBASE: true
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
